version: "3.9"

services:
  bot:
    build:
      context: ./WorkoutBot/bot
      dockerfile: Dockerfile
    container_name: bot
    networks:
      - app-network
    environment:
      TELEGRAM_TOKEN: 8323906750:AAEg2xVPwz17GcFJmvPMdCPhygCb17S0Elo
      SERVER_HOST: "server:50051"
      AI_HOST: "ai:50051"
  ai:
    build:
      context: ./WorkoutAIStat
      dockerfile: Dockerfile
    ports:
      - 50000:50051
    container_name: ai
    networks:
      - app-network
    environment:
      AI_API_KEY: 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
  web:
    build:
      context: ./Web
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    container_name: web
    networks:
      - app-network
    environment:
      CLIENT_ADDR: "server:50051"
  server:
    build: 
      context: ./WorkoutServer
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "50051:50051"
    networks:
      - app-network
    environment:
      DB_USER: Work
      DB_PASSWORD: 27112007_gg
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: workout
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: Work
      POSTGRES_PASSWORD: 27112007_gg
      POSTGRES_DB: workout
    ports:
       - "5432:5432"
    networks:
       - app-network

networks:
  app-network:
    driver: bridge