// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: proto/kach.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddResRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	User           string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SportsExercise []*Podhpowt            `protobuf:"bytes,2,rep,name=sports_exercise,json=sportsExercise,proto3" json:"sports_exercise,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddResRequest) Reset() {
	*x = AddResRequest{}
	mi := &file_proto_kach_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResRequest) ProtoMessage() {}

func (x *AddResRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResRequest.ProtoReflect.Descriptor instead.
func (*AddResRequest) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{0}
}

func (x *AddResRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AddResRequest) GetSportsExercise() []*Podhpowt {
	if x != nil {
		return x.SportsExercise
	}
	return nil
}

type Podhpowt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upr           string                 `protobuf:"bytes,1,opt,name=upr,proto3" json:"upr,omitempty"`
	Ves           float64                `protobuf:"fixed64,2,opt,name=ves,proto3" json:"ves,omitempty"`
	Podh          int64                  `protobuf:"varint,3,opt,name=podh,proto3" json:"podh,omitempty"`
	Powt          int64                  `protobuf:"varint,4,opt,name=powt,proto3" json:"powt,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Podhpowt) Reset() {
	*x = Podhpowt{}
	mi := &file_proto_kach_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Podhpowt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Podhpowt) ProtoMessage() {}

func (x *Podhpowt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Podhpowt.ProtoReflect.Descriptor instead.
func (*Podhpowt) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{1}
}

func (x *Podhpowt) GetUpr() string {
	if x != nil {
		return x.Upr
	}
	return ""
}

func (x *Podhpowt) GetVes() float64 {
	if x != nil {
		return x.Ves
	}
	return 0
}

func (x *Podhpowt) GetPodh() int64 {
	if x != nil {
		return x.Podh
	}
	return 0
}

func (x *Podhpowt) GetPowt() int64 {
	if x != nil {
		return x.Powt
	}
	return 0
}

func (x *Podhpowt) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type AddResResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otv           string                 `protobuf:"bytes,1,opt,name=otv,proto3" json:"otv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResResponse) Reset() {
	*x = AddResResponse{}
	mi := &file_proto_kach_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResResponse) ProtoMessage() {}

func (x *AddResResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResResponse.ProtoReflect.Descriptor instead.
func (*AddResResponse) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{2}
}

func (x *AddResResponse) GetOtv() string {
	if x != nil {
		return x.Otv
	}
	return ""
}

type GetResRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Upr           []string               `protobuf:"bytes,2,rep,name=upr,proto3" json:"upr,omitempty"`
	Nachalo       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=nachalo,proto3" json:"nachalo,omitempty"`
	Konec         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=konec,proto3" json:"konec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResRequest) Reset() {
	*x = GetResRequest{}
	mi := &file_proto_kach_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResRequest) ProtoMessage() {}

func (x *GetResRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResRequest.ProtoReflect.Descriptor instead.
func (*GetResRequest) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{3}
}

func (x *GetResRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GetResRequest) GetUpr() []string {
	if x != nil {
		return x.Upr
	}
	return nil
}

func (x *GetResRequest) GetNachalo() *timestamppb.Timestamp {
	if x != nil {
		return x.Nachalo
	}
	return nil
}

func (x *GetResRequest) GetKonec() *timestamppb.Timestamp {
	if x != nil {
		return x.Konec
	}
	return nil
}

type GetResResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Get                 `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResResponse) Reset() {
	*x = GetResResponse{}
	mi := &file_proto_kach_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResResponse) ProtoMessage() {}

func (x *GetResResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResResponse.ProtoReflect.Descriptor instead.
func (*GetResResponse) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{4}
}

func (x *GetResResponse) GetResults() []*Get {
	if x != nil {
		return x.Results
	}
	return nil
}

type Get struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upr           string                 `protobuf:"bytes,1,opt,name=upr,proto3" json:"upr,omitempty"`
	Slab          float64                `protobuf:"fixed64,2,opt,name=slab,proto3" json:"slab,omitempty"`
	Siln          float64                `protobuf:"fixed64,3,opt,name=siln,proto3" json:"siln,omitempty"`
	Sr            float64                `protobuf:"fixed64,4,opt,name=sr,proto3" json:"sr,omitempty"`
	Raznica       float64                `protobuf:"fixed64,5,opt,name=raznica,proto3" json:"raznica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get) Reset() {
	*x = Get{}
	mi := &file_proto_kach_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{5}
}

func (x *Get) GetUpr() string {
	if x != nil {
		return x.Upr
	}
	return ""
}

func (x *Get) GetSlab() float64 {
	if x != nil {
		return x.Slab
	}
	return 0
}

func (x *Get) GetSiln() float64 {
	if x != nil {
		return x.Siln
	}
	return 0
}

func (x *Get) GetSr() float64 {
	if x != nil {
		return x.Sr
	}
	return 0
}

func (x *Get) GetRaznica() float64 {
	if x != nil {
		return x.Raznica
	}
	return 0
}

type Uprajnenie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upr           string                 `protobuf:"bytes,1,opt,name=upr,proto3" json:"upr,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uprajnenie) Reset() {
	*x = Uprajnenie{}
	mi := &file_proto_kach_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uprajnenie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uprajnenie) ProtoMessage() {}

func (x *Uprajnenie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uprajnenie.ProtoReflect.Descriptor instead.
func (*Uprajnenie) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{6}
}

func (x *Uprajnenie) GetUpr() string {
	if x != nil {
		return x.Upr
	}
	return ""
}

func (x *Uprajnenie) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Top struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           []*Dinah               `protobuf:"bytes,1,rep,name=top,proto3" json:"top,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Top) Reset() {
	*x = Top{}
	mi := &file_proto_kach_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Top) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Top) ProtoMessage() {}

func (x *Top) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Top.ProtoReflect.Descriptor instead.
func (*Top) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{7}
}

func (x *Top) GetTop() []*Dinah {
	if x != nil {
		return x.Top
	}
	return nil
}

type Dinah struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Ves           float64                `protobuf:"fixed64,2,opt,name=ves,proto3" json:"ves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dinah) Reset() {
	*x = Dinah{}
	mi := &file_proto_kach_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dinah) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dinah) ProtoMessage() {}

func (x *Dinah) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kach_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dinah.ProtoReflect.Descriptor instead.
func (*Dinah) Descriptor() ([]byte, []int) {
	return file_proto_kach_proto_rawDescGZIP(), []int{8}
}

func (x *Dinah) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Dinah) GetVes() float64 {
	if x != nil {
		return x.Ves
	}
	return 0
}

var File_proto_kach_proto protoreflect.FileDescriptor

const file_proto_kach_proto_rawDesc = "" +
	"\n" +
	"\x10proto/kach.proto\x12\x04kach\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\rAddResRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x127\n" +
	"\x0fsports_exercise\x18\x02 \x03(\v2\x0e.kach.podhpowtR\x0esportsExercise\"\x86\x01\n" +
	"\bpodhpowt\x12\x10\n" +
	"\x03upr\x18\x01 \x01(\tR\x03upr\x12\x10\n" +
	"\x03ves\x18\x02 \x01(\x01R\x03ves\x12\x12\n" +
	"\x04podh\x18\x03 \x01(\x03R\x04podh\x12\x12\n" +
	"\x04powt\x18\x04 \x01(\x03R\x04powt\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\"\n" +
	"\x0eAddResResponse\x12\x10\n" +
	"\x03otv\x18\x01 \x01(\tR\x03otv\"\x9d\x01\n" +
	"\rGetResRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03upr\x18\x02 \x03(\tR\x03upr\x124\n" +
	"\anachalo\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\anachalo\x120\n" +
	"\x05konec\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05konec\"5\n" +
	"\x0eGetResResponse\x12#\n" +
	"\aresults\x18\x01 \x03(\v2\t.kach.GetR\aresults\"i\n" +
	"\x03Get\x12\x10\n" +
	"\x03upr\x18\x01 \x01(\tR\x03upr\x12\x12\n" +
	"\x04slab\x18\x02 \x01(\x01R\x04slab\x12\x12\n" +
	"\x04siln\x18\x03 \x01(\x01R\x04siln\x12\x0e\n" +
	"\x02sr\x18\x04 \x01(\x01R\x02sr\x12\x18\n" +
	"\araznica\x18\x05 \x01(\x01R\araznica\"4\n" +
	"\n" +
	"Uprajnenie\x12\x10\n" +
	"\x03upr\x18\x01 \x01(\tR\x03upr\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"$\n" +
	"\x03Top\x12\x1d\n" +
	"\x03top\x18\x01 \x03(\v2\v.kach.dinahR\x03top\"-\n" +
	"\x05dinah\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03ves\x18\x02 \x01(\x01R\x03ves2\xa1\x01\n" +
	"\fOrderService\x123\n" +
	"\x06AddRes\x12\x13.kach.AddResRequest\x1a\x14.kach.AddResResponse\x123\n" +
	"\x06GetRes\x12\x13.kach.GetResRequest\x1a\x14.kach.GetResResponse\x12'\n" +
	"\bTopUsers\x12\x10.kach.Uprajnenie\x1a\t.kach.TopB\bZ\x06proto/b\x06proto3"

var (
	file_proto_kach_proto_rawDescOnce sync.Once
	file_proto_kach_proto_rawDescData []byte
)

func file_proto_kach_proto_rawDescGZIP() []byte {
	file_proto_kach_proto_rawDescOnce.Do(func() {
		file_proto_kach_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kach_proto_rawDesc), len(file_proto_kach_proto_rawDesc)))
	})
	return file_proto_kach_proto_rawDescData
}

var file_proto_kach_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_kach_proto_goTypes = []any{
	(*AddResRequest)(nil),         // 0: kach.AddResRequest
	(*Podhpowt)(nil),              // 1: kach.podhpowt
	(*AddResResponse)(nil),        // 2: kach.AddResResponse
	(*GetResRequest)(nil),         // 3: kach.GetResRequest
	(*GetResResponse)(nil),        // 4: kach.GetResResponse
	(*Get)(nil),                   // 5: kach.Get
	(*Uprajnenie)(nil),            // 6: kach.Uprajnenie
	(*Top)(nil),                   // 7: kach.Top
	(*Dinah)(nil),                 // 8: kach.dinah
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_kach_proto_depIdxs = []int32{
	1, // 0: kach.AddResRequest.sports_exercise:type_name -> kach.podhpowt
	9, // 1: kach.podhpowt.date:type_name -> google.protobuf.Timestamp
	9, // 2: kach.GetResRequest.nachalo:type_name -> google.protobuf.Timestamp
	9, // 3: kach.GetResRequest.konec:type_name -> google.protobuf.Timestamp
	5, // 4: kach.GetResResponse.results:type_name -> kach.Get
	8, // 5: kach.Top.top:type_name -> kach.dinah
	0, // 6: kach.OrderService.AddRes:input_type -> kach.AddResRequest
	3, // 7: kach.OrderService.GetRes:input_type -> kach.GetResRequest
	6, // 8: kach.OrderService.TopUsers:input_type -> kach.Uprajnenie
	2, // 9: kach.OrderService.AddRes:output_type -> kach.AddResResponse
	4, // 10: kach.OrderService.GetRes:output_type -> kach.GetResResponse
	7, // 11: kach.OrderService.TopUsers:output_type -> kach.Top
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_kach_proto_init() }
func file_proto_kach_proto_init() {
	if File_proto_kach_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kach_proto_rawDesc), len(file_proto_kach_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kach_proto_goTypes,
		DependencyIndexes: file_proto_kach_proto_depIdxs,
		MessageInfos:      file_proto_kach_proto_msgTypes,
	}.Build()
	File_proto_kach_proto = out.File
	file_proto_kach_proto_goTypes = nil
	file_proto_kach_proto_depIdxs = nil
}
