// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/ai.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Podhpowt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upr           string                 `protobuf:"bytes,1,opt,name=upr,proto3" json:"upr,omitempty"`
	Ves           float64                `protobuf:"fixed64,2,opt,name=ves,proto3" json:"ves,omitempty"`
	Podh          int64                  `protobuf:"varint,3,opt,name=podh,proto3" json:"podh,omitempty"`
	Powt          int64                  `protobuf:"varint,4,opt,name=powt,proto3" json:"powt,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Podhpowt) Reset() {
	*x = Podhpowt{}
	mi := &file_proto_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Podhpowt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Podhpowt) ProtoMessage() {}

func (x *Podhpowt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Podhpowt.ProtoReflect.Descriptor instead.
func (*Podhpowt) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{0}
}

func (x *Podhpowt) GetUpr() string {
	if x != nil {
		return x.Upr
	}
	return ""
}

func (x *Podhpowt) GetVes() float64 {
	if x != nil {
		return x.Ves
	}
	return 0
}

func (x *Podhpowt) GetPodh() int64 {
	if x != nil {
		return x.Podh
	}
	return 0
}

func (x *Podhpowt) GetPowt() int64 {
	if x != nil {
		return x.Powt
	}
	return 0
}

func (x *Podhpowt) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Stat          []*Podhpowt            `protobuf:"bytes,2,rep,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GetRequest) GetStat() []*Podhpowt {
	if x != nil {
		return x.Stat
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GetResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_ai_proto protoreflect.FileDescriptor

const file_proto_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ai.proto\x12\x02ai\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\bPodhpowt\x12\x10\n" +
	"\x03upr\x18\x01 \x01(\tR\x03upr\x12\x10\n" +
	"\x03ves\x18\x02 \x01(\x01R\x03ves\x12\x12\n" +
	"\x04podh\x18\x03 \x01(\x03R\x04podh\x12\x12\n" +
	"\x04powt\x18\x04 \x01(\x03R\x04powt\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"B\n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12 \n" +
	"\x04stat\x18\x02 \x03(\v2\f.ai.PodhpowtR\x04stat\"=\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse26\n" +
	"\fOrderService\x12&\n" +
	"\x03Get\x12\x0e.ai.GetRequest\x1a\x0f.ai.GetResponseB\x1bZ\x19workoutserver/proto;protob\x06proto3"

var (
	file_proto_ai_proto_rawDescOnce sync.Once
	file_proto_ai_proto_rawDescData []byte
)

func file_proto_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)))
	})
	return file_proto_ai_proto_rawDescData
}

var file_proto_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ai_proto_goTypes = []any{
	(*Podhpowt)(nil),              // 0: ai.Podhpowt
	(*GetRequest)(nil),            // 1: ai.GetRequest
	(*GetResponse)(nil),           // 2: ai.GetResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_ai_proto_depIdxs = []int32{
	3, // 0: ai.Podhpowt.date:type_name -> google.protobuf.Timestamp
	0, // 1: ai.GetRequest.stat:type_name -> ai.Podhpowt
	1, // 2: ai.OrderService.Get:input_type -> ai.GetRequest
	2, // 3: ai.OrderService.Get:output_type -> ai.GetResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ai_proto_init() }
func file_proto_ai_proto_init() {
	if File_proto_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_proto = out.File
	file_proto_ai_proto_goTypes = nil
	file_proto_ai_proto_depIdxs = nil
}
